version: '3.8'

services:
  db:
    image: mysql:8.0.36
    container_name: mysql-container
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      #MYSQL_PASSWORD: 'root'
      #MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: fleetmanagement
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - springnet
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: backend-spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - db
   # environment:
    #  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fleetmanagement?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #  SPRING_DATASOURCE_USERNAME: root
    #  SPRING_DATASOURCE_PASSWORD: root
    networks:
      - springnet

volumes:
  db-data:

networks:
  springnet: